### Listar Cidades
GET http://localhost:3000/cidades

### Criar cidade
POST http://localhost:3000/cidades
Content-Type: application/json

{
  "nomeCidade": "Niterói",
  "ufSigla": "RJ"
}

### Deletar cidade
DELETE http://localhost:3000/cidades/cid_hgSUb49HxF479jseqF0w5