### Criar Usuario
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "username": "Teste",
    "senha": "123",
    "email": "teste@mail.com"
}

### Atualizar Usuario
PATCH http://localhost:3000/usuario/userID_whlLXWfi7sTV7V2LSEepx
Content-Type: application/json

{
    "username": "Gabriel Cézar"
}

### Listar Usuarios
GET http://localhost:3000/usuario/

### Deletar Usuario
DELETE http://localhost:3000/usuario/7